name: "Multi Event Pipeline"

on:
    push:
        branches:
            - master
            - test
    pull_request:
        branches:
            - master
        types:
            - closed
            - opened

    workflow_dispatch:


jobs:
    on-push:
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - name: "Multi Pipeline"
              run: echo "running on master/test push" 
    on-pull-request:
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps:
            - name: "Multi Pipeline"
              run: echo "running on master pull requset"
    on-pull-request-closed:
        if: github.event_name == 'pull-request' && github.event.action == 'closed'
        runs-on: "ubuntu-latest"
        steps:
            - name: "running on pull closed"
              run: echo "Running on pull closed"

    on-workflow-dispatched:
        if: github.event_name == 'workflow_dispatch'
        runs-on: "ubuntu-latest"
        steps:
            - name: "On flow dispatched"
              run: echo "Running on event workflow dispatched"

